name: Main

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Publish to nuget
        type: boolean
        required: false
        default: false
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 7.0.x
    - name: Compile
      run: ./build.sh Compile CompileWatcher --no-logo
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      with:
        limit-access-to-actor: true
    
    - name: Upload NuGet
      if: ${{ inputs.publish }}
      run: dotnet nuget push "local-nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
